"""add_icon_url_to_blogs

Revision ID: 1cdfe9d0a272
Revises: 312565cb7753
Create Date: 2026-03-02 02:33:04.144239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cdfe9d0a272'
down_revision: Union[str, None] = '312565cb7753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('icon_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'icon_url')
    # ### end Alembic commands ###
