"""Add reading_time to blog posts

Revision ID: 3b41b30be48b
Revises: 7b0ad53c5f97
Create Date: 2026-02-08 22:54:17.809056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b41b30be48b'
down_revision: Union[str, None] = '7b0ad53c5f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('reading_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'reading_time')
    # ### end Alembic commands ###
