/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as UnsubscribeIdRouteImport } from './routes/unsubscribe.$id'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEditIdRouteImport } from './routes/admin/edit.$id'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeIdRoute = UnsubscribeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UnsubscribeRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/unsubscribe/$id': typeof UnsubscribeIdRoute
  '/about': typeof AboutIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/unsubscribe/$id': typeof UnsubscribeIdRoute
  '/about': typeof AboutIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/unsubscribe/$id': typeof UnsubscribeIdRoute
  '/about/': typeof AboutIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/unsubscribe'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/new'
    | '/blog/$slug'
    | '/unsubscribe/$id'
    | '/about'
    | '/admin/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/unsubscribe'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/new'
    | '/blog/$slug'
    | '/unsubscribe/$id'
    | '/about'
    | '/admin/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/unsubscribe'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/new'
    | '/blog/$slug'
    | '/unsubscribe/$id'
    | '/about/'
    | '/admin/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  UnsubscribeRoute: typeof UnsubscribeRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$id': {
      id: '/unsubscribe/$id'
      path: '/$id'
      fullPath: '/unsubscribe/$id'
      preLoaderRoute: typeof UnsubscribeIdRouteImport
      parentRoute: typeof UnsubscribeRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UnsubscribeRouteChildren {
  UnsubscribeIdRoute: typeof UnsubscribeIdRoute
}

const UnsubscribeRouteChildren: UnsubscribeRouteChildren = {
  UnsubscribeIdRoute: UnsubscribeIdRoute,
}

const UnsubscribeRouteWithChildren = UnsubscribeRoute._addFileChildren(
  UnsubscribeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  UnsubscribeRoute: UnsubscribeRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
